CREATE OR REPLACE FUNCTION super_age (int) RETURNS boolean as 
$$
BEGIN 
    IF $1%2=0 AND POWER ($1,2)< 1000 AND SQRT ($1)>5 THEN
      RETURN TRUE;
    END IF;
RETURN FALSE;
END;
$$
LANGUAGE PLPGSQL IMMUTABLE;
